import {recordLabel} from './festival-copy.mjs';
import * as THREE from 'three';
import {LakeAdventure} from './lake-adventure.mjs';
import {clueCard} from './festival-clues.mjs';
import {SkillMixer} from './skill-mixer.mjs';
import {RobotRepair,REPAIR_PARTS} from './robot-repair.mjs';
import {FestivalConcert} from './festival-concert.mjs';
import {FestivalReactions} from './festival-reactions.mjs';
import {KickBall,migrateRound,beginRound,ROUND_STEPS,finishActivity,nextActivity,finishRound,concertUnlocked} from './festival-simulation.mjs';
const names={kick:'Kick the globe',records:'Spin a record',aid:'Help the robot',maker:'Build a useful skill',canoe:'Across the lake',finale:'Meet at the stage'};
const records=['Communicate','Solve','Create','Connect','Stay curious'];
export class FestivalPlay {
 constructor(engine,host){
  this.e=engine;this.h=host;this.concert=new FestivalConcert(engine,engine.jamKit,{reduced:host.reduced});this.active=null;this.keys=new Set();this.clock=0;this.reduced=host.reduced;this.kit=engine.jamKit;
  let saved;try{saved=JSON.parse(localStorage.getItem('skillsjam.round.v1'));}catch{}this.state=migrateRound(saved);
  this.root=new THREE.Group();this.root.name='FestivalActivities';engine.scene.add(this.root);
  this.ballMesh=this.kit.instances.get('kickball');const size=new THREE.Box3().setFromObject(this.ballMesh).getSize(new THREE.Vector3());this.ball=new KickBall({radius:Math.max(size.x,size.y,size.z)/2,obstacles:[{x:-5.4,z:25.1,r:.45,height:.6},{x:-10,z:26,r:.7,height:1}]});this.ball.reset();this.ballMesh.position.fromArray(this.ball.p);this.hero=this.kit.instances.get('hero');this.syncHeroVisibility();this.kit.play('hero','idle');this.kit.controlledBall=true;
  this.marker=new THREE.Group();this.marker.name='KickTargets';this.root.add(this.marker);this.targets=[];
  for(let i=0;i<3;i++){const m=new THREE.Mesh(new THREE.TorusGeometry(.9,.045,6,40),new THREE.MeshStandardMaterial({color:['#1b7d78','#c85a3f','#cb9227'][i],roughness:.9}));m.rotation.x=-Math.PI/2;m.position.y=.05;this.marker.add(m);this.targets.push(m);}
  this.path=new THREE.Line(new THREE.BufferGeometry(),new THREE.LineDashedMaterial({color:'#185a56',dashSize:.16,gapSize:.12,depthTest:false}));this.path.renderOrder=5;this.root.add(this.path);this.marker.visible=this.path.visible=false;
  this.recordHomes=new Map(records.map(n=>{const o=this.kit.instances.get('record_'+n.toLowerCase().replaceAll(' ','_'));return[n,{o,p:o.position.clone(),q:o.quaternion.clone()}];}));
  this.deck=new THREE.Mesh(new THREE.CylinderGeometry(.19,.19,.035,32),new THREE.MeshStandardMaterial({color:'#254c48',roughness:.7}));this.deck.position.set(11.75,.94,26.06);this.root.add(this.deck);
  this.reactions=new FestivalReactions(this.kit,{reduced:this.reduced,repaired:this.state.robotRepaired});this.repair=new RobotRepair(engine,this.kit.instances.get('robot'),{home:this.reactions.robotHome,reduced:this.reduced,onFit:()=>this.h.chime(),onComplete:()=>{this.state.robotRepaired=true;this.reactions.repaired(this.clock);this.result('aid','Your friend is awake!');}});
  this.adventure=new LakeAdventure(engine,this.kit,{reduced:this.reduced,getDusk:host.getDusk,setDusk:host.setDusk,playMusic:host.playCamp,endMusic:host.endCampMusic,musicState:host.musicState,toggleMusic:host.toggleMusic,onWake:()=>{this.state.overnights=(this.state.overnights||0)+1;this.save();this.exit(false);this.h.wakeAtFestival?.();}});
  this.mixer=new SkillMixer(engine,this.kit,{reduced:this.reduced,onPour:()=>this.h.chime(),onWin:()=>{this.h.chime();this.reactions.celebrate(this.clock);},onComplete:()=>this.result('maker','Three useful skills. Three happy outcomes!')});
  this.ui=document.createElement('section');this.ui.id='festivalPlay';this.ui.hidden=true;this.ui.setAttribute('aria-label','Festival activity');document.body.append(this.ui);
  this.launch=document.createElement('button');this.launch.id='roundLaunch';this.launch.className='round-launch';this.launch.onclick=()=>this.h.showJournal?.();document.getElementById('hud').append(this.launch);this.syncLaunch();
  this.raycaster=new THREE.Raycaster();engine.canvas.addEventListener('pointerdown',event=>{if(!this.active)return;event.stopImmediatePropagation();if(this.active==='records'&&this.recordPhase!=='playing'){const r=engine.canvas.getBoundingClientRect();this.raycaster.setFromCamera(new THREE.Vector2((event.clientX-r.left)/r.width*2-1,-(event.clientY-r.top)/r.height*2+1),engine.camera);const hit=this.raycaster.intersectObjects([...this.recordHomes.values()].map(v=>v.o),true)[0];if(hit){let node=hit.object;while(node&&!records.some(n=>this.recordHomes.get(n).o===node))node=node.parent;const index=records.findIndex(n=>this.recordHomes.get(n).o===node);if(index>=0)this.ui.querySelector(`[data-record="${index}"]`).click();}}},true);
  this.profile=[];this.lastFrame=0;this.qa=new URLSearchParams(location.search).has('playQA');if(this.qa){this.qaText=document.createElement('output');this.qaText.id='playMetrics';this.qaText.style='position:fixed;right:12px;top:155px;z-index:18;background:#fff5dc;padding:8px;font:12px monospace;max-width:260px;white-space:normal;overflow-wrap:anywhere';document.body.append(this.qaText);const capture=document.createElement('button');capture.textContent='Save QA frame';capture.style='position:fixed;right:12px;top:280px;z-index:18;padding:10px';document.body.append(capture);capture.onclick=async()=>{const name='play_'+(this.active||'entrance');const png=await new Promise(resolve=>engine.canvas.toBlob(resolve,'image/png'));const response=await fetch('/__kit_capture/'+name,{method:'POST',headers:{'Content-Type':'image/png'},body:png});capture.textContent=response.ok?'QA frame saved':'Capture unavailable';};}

  window.addEventListener('keydown',e=>this.key(e,true),true);window.addEventListener('keyup',e=>this.key(e,false),true);
  window.addEventListener('blur',()=>this.clearInput());document.addEventListener('visibilitychange',()=>this.clearInput());
 }
 save(){try{localStorage.setItem('skillsjam.round.v1',JSON.stringify(this.state));}catch{}this.syncLaunch();}
 syncLaunch(){this.launch.textContent=concertUnlocked(this.state)?'Headliner ready · Meet at the stage':`Headliner clues · ${this.state.completed.length}/${ROUND_STEPS.length}`;}
 journal(){return clueCard(this.state.completed);}
 canAttendConcert(){return concertUnlocked(this.state);}
 clearInput(){this.keys.clear();this.charging=false;this.repair?.cancel();this.mixer?.cancel();this.adventure?.keys.clear();if(this.adventure?.journey)this.adventure.journey.held=false;}
 startRound(){this.exit(false);this.finaleAt=0;if(!this.state.active){beginRound(this.state);this.save();}this.h.prepare();this.h.welcomeClues?.();}
 continueRound(){if(!this.state.active)this.startRound();this.h.showJournal?.();}
 complete(id){finishActivity(this.state,id);if(id!=='kick')this.h.award(id);this.save();this.reactUntil=this.clock+2.5;this.reactions.celebrate(this.clock,id==='aid'?'repair':id==='records'?'record':'success');this.h.chime();}
 open(id){
  if(!['kick','records','aid','maker','finale','canoe'].includes(id))return false;
  this.exit(false);this.h.prepare();if(!this.state.active&&!concertUnlocked(this.state)&&ROUND_STEPS.includes(id)){beginRound(this.state);this.save();}this.active=id;this.syncHeroVisibility();this.ui.hidden=false;document.getElementById('toast').classList.remove('show');document.body.classList.add('playing-activity');this.ui.dataset.activity=id;this.savedHero={p:this.hero.position.clone(),q:this.hero.quaternion.clone()};
  this.ui.innerHTML=`<div class="play-head"><div><small>PROMPTSTOCK · DAY ${this.state.day}</small><h2>${names[id]}</h2><p id="playHint"></p></div><span class="play-navigation"><button data-action="menu">Main menu</button><button data-action="exit" aria-label="Return to wandering">✕</button></span></div><div class="play-dock" id="playDock"></div>`;
  this.ui.querySelector('[data-action=exit]').onclick=()=>this.exit();this.ui.querySelector('[data-action=menu]').onclick=()=>this.h.mainMenu?.();
  if(id==='kick')this.setupKick();else if(id==='records')this.setupRecords();else if(id==='aid')this.setupAid();else if(id==='maker')this.setupMaker();else if(id==='canoe'){this.adventure.open(this.ui);}else this.setupFinale();
  this.profile=[];this.lastFrame=0;this.ui.querySelector('button')?.focus();return true;
 }
 hint(s){this.ui.querySelector('#playHint').textContent=s;}
 dock(html){this.ui.querySelector('#playDock').innerHTML=html;}
 button(id,fn){this.ui.querySelector('#'+id).onclick=fn;}
 result(id,message){this.complete(id);const ready=concertUnlocked(this.state);this.hint(ready?'Three acts of kindness. Follow the path behind the tents: the headliner is ready.':message+' Find your next clue on the lawn.');this.ui.querySelector('#playDock').insertAdjacentHTML('beforeend',`<div class="activity-success" role="status"><strong>${message}</strong><button id="playNext">${ready?'Back to the lawn · Find the stage':'Back to exploring'}</button></div>`);this.button('playNext',()=>this.exit());this.ui.querySelector('#playNext').focus({preventScroll:true});}
 setupKick(){
  this.hint('Land the globe inside each ring. Aim with ← →. Hold Space and release to kick.');this.score=0;this.shots=0;this.hit=new Set();this.shotDone=false;this.kickTimer=-1;this.aim=0;this.power=.4;
  const shift=(this.state.day-1)%3-1;[[-1+shift,20],[4-shift,17],[1+shift,14]].forEach((p,i)=>{this.targets[i].position.set(p[0],.045,p[1]);this.targets[i].material.color.set(['#167d76','#d25435','#c49624'][i]);});this.marker.visible=true;this.hero.position.set(1,0,27.65);this.hero.rotation.y=Math.PI;this.kit.play('hero','idle');this.resetBall();
  this.dock(`<div class="course-score"><strong id="kickScore">0 / 3 rings</strong><span id="shotCount">0 kicks · best ${this.state.best}</span></div><div class="kick-controls"><label>Aim <input id="kickAim" aria-label="Kick aim" type="range" min="-45" max="45" value="0"></label><label>Power <input id="kickPower" aria-label="Kick power" type="range" min="0" max="100" value="40"></label></div><div class="play-actions"><button id="kickNow" class="primary">Kick globe</button><button id="kickAssist" disabled>Help me aim</button><button id="kickRetry">Reset ball</button></div><p class="play-note">A / D sidestep · W / S approach · Space charges · Esc leaves. Touch: use the sliders and Kick.</p>`);
  this.ui.querySelector('#kickAim').oninput=e=>{this.aim=Number(e.target.value)*Math.PI/180;this.preview();};this.ui.querySelector('#kickPower').oninput=e=>{this.power=Number(e.target.value)/100;this.preview();};
  this.button('kickNow',()=>this.kick());this.button('kickAssist',()=>{this.assist();this.hint('Try this angle and power, then make the kick.');});this.button('kickRetry',()=>this.resetBall());this.aimTarget();
 }
 resetBall(){this.ball.reset(this.hero.position.x,this.hero.position.z-.5);this.kickTimer=-1;this.shotDone=false;this.kit.play('hero','idle');this.preview();}
 aimTarget(){this.aim=0;this.power=.4;this.ui.querySelector('#kickAim').value=0;this.ui.querySelector('#kickPower').value=40;this.preview();}
 assist(){const target=this.targets.find((_,i)=>!this.hit.has(i));if(!target)return;this.aim=Math.atan2(target.position.x-this.ball.p[0],this.ball.p[2]-target.position.z);let best=Infinity;
  for(let i=0;i<=100;i++){const ps=this.ball.predict(this.aim,i/100);for(const p of ps){if(p[1]>.55)continue;const d=Math.hypot(p[0]-target.position.x,p[2]-target.position.z);if(d<best){best=d;this.power=i/100;}}}
  const a=this.ui.querySelector('#kickAim'),p=this.ui.querySelector('#kickPower');if(a)a.value=this.aim*180/Math.PI;if(p)p.value=this.power*100;this.preview();
 }
 preview(){if(this.active!=='kick'||this.ball.moving)return;const points=this.ball.predict(this.aim,this.power);this.path.geometry.dispose();this.path.geometry=new THREE.BufferGeometry().setFromPoints(points.map(p=>new THREE.Vector3(...p)));this.path.computeLineDistances();this.path.visible=true;}
 kick(){if(this.ball.moving||this.kickTimer>=0||this.hit.size===3)return;this.hero.position.set(this.ball.p[0]-Math.sin(this.aim)*.5,0,this.ball.p[2]+Math.cos(this.aim)*.5);this.hero.rotation.y=Math.PI-this.aim;this.shot={aim:this.aim,power:this.power};this.kickTimer=0;this.kit.play('hero','kick',true);this.path.visible=false;this.shots++;this.ui.querySelector('#kickAssist').disabled=this.shots<2;this.ui.querySelector('#shotCount').textContent=`${this.shots} kicks · best ${this.state.best}`;}
 scoreStep(){if(this.shotDone)return;for(let i=0;i<3;i++){const t=this.targets[i];if(!this.hit.has(i)&&this.ball.p[1]<.55&&Math.hypot(this.ball.p[0]-t.position.x,this.ball.p[2]-t.position.z)<.83){this.hit.add(i);this.shotDone=true;this.score=Math.max(0,300-(this.shots-this.hit.size)*20);t.material.color.set('#f0d570');this.reactUntil=this.clock+2;this.reactions.celebrate(this.clock);this.h.chime();this.hint(`${this.hit.size} of 3! ${this.hit.size<3?'Try the next ring.':'Every ring found.'}`);this.ui.querySelector('#kickScore').textContent=`${this.hit.size} / 3 rings`;
    if(this.hit.size===3){this.state.best=Math.max(this.state.best,this.score);this.ui.querySelector('#shotCount').textContent=`${this.shots} kicks · best ${this.state.best}`;this.result('kick',`Course complete · ${this.score} points · ${this.shots} kicks`);}this.resetAt=this.clock+1.3;break;}}}
 setupRecords(){this.recordRequest=(this.recordRequest||0)+1;this.recordPhase='choose';this.selected=null;this.recordAwarded=false;this.hint('Lift a record, then place it on the turntable to play its song.');this.dock(`<div class="record-picks">${records.map((n,i)=>`<button data-record="${i}">${recordLabel(n)}</button>`).join('')}</div><p id="recordRead" class="record-read">Five records. Five songs. Pick your next spin.</p><p id="recordPlayback" role="status"></p><div class="play-actions"><button id="recordPlace" class="primary" disabled>Place & play</button><button id="recordPause">Pause music</button><button id="recordBack">Return to crate</button></div>`);
  this.ui.querySelectorAll('[data-record]').forEach(b=>b.onclick=()=>{if(this.recordPhase==='loading')return;this.restoreRecords();this.selected=records[Number(b.dataset.record)];this.recordPhase='inspect';this.ui.querySelectorAll('[data-record]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));this.ui.querySelector('#recordRead').textContent=recordLabel(this.selected).toUpperCase()+' · '+({Communicate:'Explain one useful idea simply.',Solve:'Break a problem into one manageable step.',Create:'Make a small first draft.',Connect:'Invite someone to share a useful tip.','Stay curious':'Ask one question you have not asked before.'}[this.selected]);this.ui.querySelector('#recordPlace').disabled=false;this.ui.querySelector('#recordPlace').textContent='Place & play';});
  this.button('recordBack',()=>{if(this.recordPhase==='loading')return;this.restoreRecords();this.selected=null;this.recordPhase='choose';this.ui.querySelector('#recordPlace').disabled=true;this.ui.querySelector('#recordRead').textContent='Choose another record.';});
  this.button('recordPause',()=>this.h.toggleMusic?.());
  this.button('recordPlace',async()=>{
   if(!this.selected||this.recordPhase!=='inspect')return;const selected=this.selected,request=++this.recordRequest;
   this.recordPhase='loading';this.hint(`Loading ${recordLabel(selected)}…`);this.ui.querySelector('#recordPlace').disabled=true;this.ui.querySelector('#recordPlace').textContent='Loading…';this.setRecordChoicesDisabled(true);
   const ok=await this.h.playRecord?.(selected);
   if(request!==this.recordRequest||this.active!=='records'||this.selected!==selected||this.recordPhase!=='loading')return;
   this.setRecordChoicesDisabled(false);
   if(!ok){this.recordPhase='inspect';this.ui.querySelector('#recordPlace').disabled=false;this.ui.querySelector('#recordPlace').textContent='Retry record';this.hint('Music did not start. Retry or choose another record.');return;}
   this.recordPhase='playing';this.h.record(selected);this.ui.querySelector('#recordPlace').textContent='On the turntable';
   if(!this.recordAwarded){this.recordAwarded=true;this.result('records','A record shared. Your stamp is ready.');}else this.hint(`${recordLabel(selected)} is playing.`);
   this.syncRecordAudio();
  });this.syncRecordAudio();
 }
 setRecordChoicesDisabled(disabled){this.ui.querySelector('#recordBack').disabled=disabled;this.ui.querySelectorAll('[data-record]').forEach(x=>x.disabled=disabled);}
 syncRecordAudio(){if(this.active!=='records')return;const state=this.h.musicState?.();if(!state)return;const status=this.ui.querySelector('#recordPlayback'),button=this.ui.querySelector('#recordPause');if(this.recordPhase==='playing')this.hint(state.status==='playing'?`${recordLabel(state.title)} is playing. Enjoy the song or choose another.`:state.status==='paused'?`${recordLabel(state.title)} is paused.`:state.status==='loading'?`Loading ${recordLabel(state.title)}…`:'Music could not play. Press Retry music.');if(status)status.textContent=state.status==='error'?`${recordLabel(state.title)} could not play. Retry the record.`:`${recordLabel(state.title)} · ${state.status}`;if(button){button.textContent=state.status==='playing'?'Pause music':state.status==='loading'?'Cancel loading':state.status==='error'?'Retry music':'Resume music';button.disabled=!state.src;}}
 restoreRecords(){for(const {o,p,q} of this.recordHomes.values()){o.position.copy(p);o.quaternion.copy(q);}}
 setupAid(){
  this.hint('Fit three parts. Line up the gold markers. Wake your friend.');
  this.dock(`<div class="repair-top"><strong id="repairCount">0 / 3 fitted</strong><span id="repairStatus" role="status">Drag a part onto its matching socket.</span></div><div class="repair-controls"><div class="repair-picks">${REPAIR_PARTS.map((p,i)=>`<button data-repair-part="${p.id}" aria-label="Select ${p.name}" style="--part:${p.color}"><span>${p.symbol}</span><small>${p.name}</small><kbd>${i+1}</kbd></button>`).join('')}</div><div class="repair-tools"><button id="repairRotate" disabled>Rotate ↻ <kbd>R</kbd></button><button id="repairFit" disabled>Fit part <kbd>Enter</kbd></button><button id="repairPower" class="primary" disabled>POWER</button></div></div><p class="repair-tip">Drag to fit · or select a part, rotate, then press Fit.</p>`);
  this.reactions.beginRepair();this.state.robotRepaired=false;this.save();this.repair.open(this.state.day,this.ui);this.repair.camera();
  this.ui.querySelectorAll('[data-repair-part]').forEach(b=>b.onclick=()=>this.repair.select(b.dataset.repairPart));this.button('repairRotate',()=>this.repair.rotate());this.button('repairFit',()=>this.repair.fit());
  const power=this.ui.querySelector('#repairPower');power.setAttribute('aria-label','Power on robot. Hold with pointer or press Enter.');power.onpointerdown=e=>{if(power.disabled)return;e.preventDefault();power.setPointerCapture(e.pointerId);this.repair.held=true;};power.onpointerup=power.onpointercancel=power.onlostpointercapture=()=>this.repair.held=false;
  power.onkeydown=e=>{if(['Space','Enter'].includes(e.code)){e.preventDefault();this.repair.held=true;}};power.onkeyup=e=>{if(e.code==='Space'){e.preventDefault();this.repair.held=false;}};
 }
 setupMaker(){this.mixer.open(this.ui);this.mixer.camera();const free=document.createElement('button');free.className='mix-free';free.textContent='Prompt builder';free.onclick=()=>{this.exit();this.h.freePrompt();};this.ui.querySelector('.play-navigation').prepend(free);}
 setupFinale(){if(!concertUnlocked(this.state)){this.hint('Complete all three mini-games in this round to unlock the headliner.');this.dock('<button id="resumeRound" class="primary">Continue the round</button>');this.button('resumeRound',()=>this.continueRound());return;}
  finishRound(this.state);this.save();this.previousDusk=this.h.getDusk();this.h.setDusk(1);this.concert.open();this.concertEnded=false;
  this.ui.querySelector('.play-head small').textContent='BORINQUÉN · PUERTO RICO · LIVE AT PROMPTSTOCK';this.ui.querySelector('h2').textContent='One Island One View';this.hint('You brought everyone together. This one is for you.');
  this.dock(`<div class="concert-playing"><span class="concert-dot"></span><span id="concertStatus" role="status">Taking the stage…</span><time id="concertTime">0:00 / 3:14</time></div><progress id="concertProgress" aria-label="Concert progress" value="0" max="194"></progress><div class="play-actions"><button id="concertSound" class="primary">Loading music…</button><button id="concertCamera" aria-pressed="${this.concert.steady}">${this.concert.steady?'Cinematic camera':'Steady camera'}</button><label class="concert-volume">Volume <input id="concertVolume" aria-label="Concert volume" type="range" min="0" max="1" step=".05" value="${this.h.musicState?.().volume??.65}"></label></div><div id="concertEnding" hidden><small>FESTIVAL COMPLETE</small><h3>One island. One view. All of us.</h3><p>You kicked, shared, repaired and created. Now you belong to the band.</p><div class="play-actions"><button id="concertReplay">Encore</button><button id="anotherRound">Another festival day</button><button id="keepWandering">Keep wandering</button></div></div>`);
  this.button('concertSound',()=>this.h.toggleMusic?.());this.button('concertCamera',()=>{this.concert.steady=!this.concert.steady;const b=this.ui.querySelector('#concertCamera');b.textContent=this.concert.steady?'Cinematic camera':'Steady camera';b.setAttribute('aria-pressed',String(this.concert.steady));});this.ui.querySelector('#concertVolume').oninput=e=>this.h.setMusicVolume?.(e.target.value);
  this.button('concertReplay',()=>this.open('finale'));this.button('anotherRound',()=>this.startRound());this.button('keepWandering',()=>this.exit());this.h.playFinale?.();this.syncConcertAudio();
 }
 syncConcertAudio(){if(this.active!=='finale'||!this.concert.active)return;const s=this.h.musicState?.();if(!s)return;const status=this.ui.querySelector('#concertStatus'),button=this.ui.querySelector('#concertSound');const label=s.status==='playing'?'Borinquén · One Island One View':s.status==='ended'?'Thank you, Puerto Rico.':s.status==='error'?'Tap Retry music to start the show.':s.status==='loading'?'Loading the headliner…':'Concert paused';if(status.textContent!==label)status.textContent=label;button.textContent=s.status==='playing'?'Pause concert':s.status==='error'?'Retry music':s.status==='loading'?'Cancel loading':s.status==='ended'?'Play again':'Play concert';if(s.status==='ended')this.finishConcert();}
 finishConcert(){if(this.concertEnded)return;this.concertEnded=true;this.ui.querySelector('#concertEnding').hidden=false;this.hint('The festival is complete. The connection stays.');this.ui.querySelector('#concertSound').hidden=true;this.ui.querySelector('#concertReplay').focus({preventScroll:true});}
 key(e,down){if(!this.active)return;if(e.code==='Tab'){if(!down)return;const nodes=[...this.ui.querySelectorAll('button,input')].filter(n=>!n.disabled&&n.getClientRects().length),first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}return;}
  const form=!!e.target.closest('input,button');if(e.code==='Escape'&&down){e.preventDefault();e.stopImmediatePropagation();this.exit();return;}
  if(this.active==='canoe'){this.adventure.key(e,down);e.stopImmediatePropagation();return;}
  if(this.active==='maker'){if(down)this.mixer.key(e);if(!form)e.stopImmediatePropagation();return;}
  if(this.active==='aid'){if(e.target.id==='repairPower')return;if(down&&!e.repeat){if(['Digit1','Digit2','Digit3'].includes(e.code)){e.preventDefault();this.repair.select(REPAIR_PARTS[Number(e.code.at(-1))-1].id);}if(e.code==='KeyR'){e.preventDefault();this.repair.rotate();}if(e.code==='Enter'&&!form){e.preventDefault();this.repair.fit();}}if(!form)e.stopImmediatePropagation();return;}
  if(this.active!=='kick'||(form&&e.code!=='Space'&&e.code!=='KeyW'&&e.code!=='KeyA'&&e.code!=='KeyS'&&e.code!=='KeyD')){if(!form)e.stopImmediatePropagation();return;}
  if(['Space','ArrowLeft','ArrowRight','KeyW','KeyA','KeyS','KeyD'].includes(e.code)){if(e.code==='Space'&&e.target.matches('button'))return;e.preventDefault();e.stopImmediatePropagation();if(down){this.keys.add(e.code);if(e.code==='Space'&&!e.repeat&&!this.ball.moving){this.charging=true;this.power=0;}}else{this.keys.delete(e.code);if(e.code==='Space'&&this.charging){this.charging=false;this.kick();}}}
 }
 update(dt,time){this.clock=time;
  if(this.lastFrame&&document.visibilityState==='visible'){this.profile.push((performance.now()-this.lastFrame));if(this.profile.length>600)this.profile.shift();}this.lastFrame=performance.now();
  if(this.qa&&this.e.frame%60===0)this.qaText.textContent=JSON.stringify(this.metrics());this.ambient(time,dt);
  if(!this.active)return;
  if(this.active==='kick'){
   if(this.charging){this.power=Math.min(1,this.power+dt*.7);this.ui.querySelector('#kickPower').value=this.power*100;this.preview();}
   if(!this.ball.moving&&this.kickTimer<0&&this.hit.size<3){let moved=false;const dx=(this.keys.has('KeyD')?1:0)-(this.keys.has('KeyA')?1:0),dz=(this.keys.has('KeyS')?1:0)-(this.keys.has('KeyW')?1:0);if(dx||dz){this.hero.position.x=THREE.MathUtils.clamp(this.hero.position.x+dx*dt*1.5,-2,4);this.hero.position.z=THREE.MathUtils.clamp(this.hero.position.z+dz*dt*1.5,27,30);this.ball.reset(this.hero.position.x,this.hero.position.z-.5);moved=true;}
    const turn=(this.keys.has('ArrowRight')?1:0)-(this.keys.has('ArrowLeft')?1:0);if(turn){this.aim=THREE.MathUtils.clamp(this.aim+turn*dt*.5,-.78,.78);this.ui.querySelector('#kickAim').value=this.aim*180/Math.PI;}if(moved||turn)this.preview();if(this.walking!==moved){this.kit.play('hero',moved?'walk':'idle');this.walking=moved;}}
   if(this.kickTimer>=0){const before=this.kickTimer;this.kickTimer+=dt;if(before<.5&&this.kickTimer>=.5){this.ball.kick(this.shot.aim,this.shot.power);this.h.chime();}if(this.kickTimer>1.05){this.kickTimer=-1;this.kit.play('hero','idle');}}
   this.ball.advance(dt,()=>this.scoreStep());this.ballMesh.position.fromArray(this.ball.p);if(!this.reduced&&this.ball.moving){this.ballMesh.rotation.x-=Math.hypot(this.ball.v[0],this.ball.v[2])*dt/this.ball.radius;}
   if(this.resetAt&&time>=this.resetAt){this.resetAt=0;if(this.hit.size<3){this.hero.position.set(1,0,27.65);this.resetBall();this.aimTarget();}}
   if(!this.ball.moving&&this.ball.age>0&&!this.shotDone&&this.kickTimer<0){this.hint('Close! Adjust the aim or power, or try Assist this kick.');this.resetBall();}
   if(this.e.camera.aspect<.7)this.e.setCamera([this.hero.position.x,10,this.hero.position.z+10],[this.hero.position.x,.3,22]);else this.e.setCamera([this.hero.position.x+3,7,this.hero.position.z+7],[this.hero.position.x,.6,this.e.camera.aspect>1.4?26:24]);
  }else if(this.active==='records'){
   this.e.setCamera([11.1,1.65,28.0],[11.1,1.16,26]);if(this.selected){const o=this.recordHomes.get(this.selected).o;if(this.recordPhase==='inspect'){o.position.lerp(new THREE.Vector3(11.1,1.5,26.85),this.reduced?1:1-Math.exp(-dt*10));o.quaternion.slerp(new THREE.Quaternion(),this.reduced?1:1-Math.exp(-dt*10));}else if(this.recordPhase==='playing'){o.position.lerp(new THREE.Vector3(11.75,.965,26.06),this.reduced?1:1-Math.exp(-dt*10));if(!this.recordSpin)this.recordSpin=0;if(this.h.musicPlaying?.()&&!this.reduced)this.recordSpin+=dt;o.rotation.set(-Math.PI/2,0,this.recordSpin);}}
  }else if(this.active==='aid')this.repair.update(dt,time);
  else if(this.active==='maker')this.mixer.update(dt,time);
  else if(this.active==='canoe')this.adventure.update(dt,time);
  else if(this.active==='finale'&&this.concert.active){const s=this.h.musicState?.()||{};const t=s.currentTime||0;this.concert.update(t,s.playing);const clock=n=>`${Math.floor(n/60)}:${String(Math.floor(n%60)).padStart(2,'0')}`;this.ui.querySelector('#concertTime').textContent=clock(t)+' / '+clock(s.duration||194);this.ui.querySelector('#concertProgress').value=t;this.ui.querySelector('#concertProgress').max=s.duration||194;this.syncConcertAudio();}
 }
 ambient(t,dt){if(this.concert?.active)return;this.reactions.update(dt,t,{activity:this.active,musicPlaying:this.h.musicPlaying?.()||false,finale:this.active==='finale'});
  const dog=this.kit.instances.get('dog');if(dog&&this.petUntil>t&&!this.reduced){dog.rotation.y=Math.sin(t*3)*.18;dog.position.y=Math.abs(Math.sin(t*5))*.05;}else if(dog){dog.position.y=0;dog.rotation.y=0;}
 }
 pet(){this.petUntil=this.clock+4;this.h.chime();}
 metrics(){const a=[...this.profile].sort((a,b)=>a-b),info=this.e.renderer.info;return{samples:a.length,medianFrameMs:a[Math.floor(a.length*.5)]||0,p95FrameMs:a[Math.floor(a.length*.95)]||0,drawCalls:info.render.calls,triangles:info.render.triangles,renderPath:this.e.low?'lighter':this.e.postprocessingSupported===false?'direct':'composer'};}
 syncHeroVisibility(){this.hero.visible=!!this.e.jamReview||this.active==='kick'||this.active==='finale';}
 exit(wander=true){if(!this.active)return;this.finaleAt=0;if(this.concert?.active){this.concert.close();this.h.pauseMusic?.();}this.clearInput();if(this.active==='maker')this.mixer.close();if(this.active==='canoe')this.adventure.close();if(this.active==='aid'){this.repair.close();this.reactions.leaveBench(this.repair.done===true);}this.restoreRecords();this.marker.visible=this.path.visible=false;this.resetAt=0;this.ball.reset();this.ballMesh.position.fromArray(this.ball.p);if(this.savedHero){this.hero.position.copy(this.savedHero.p);this.hero.quaternion.copy(this.savedHero.q);}this.kit.play('hero','idle');if(this.active==='finale'&&this.previousDusk!==undefined){this.h.setDusk(this.previousDusk);this.previousDusk=undefined;}this.active=null;this.syncHeroVisibility();this.ui.hidden=true;document.body.classList.remove('playing-activity');if(wander)this.h.returnToWorld();}
}
