import * as THREE from 'three';
import {clone} from 'three/addons/utils/SkeletonUtils.js';

export const MIX_CHALLENGES = [
 {id:'water',title:'Help a thirsty guest',prompt:'Bring water',context:['Thirsty guest','Dry tree'],tool:['Cup','Big watering can'],success:'A drink for our guest!',missing:'The tree got a drink. Add who needs help.',wrongContext:'Happy tree. Still-thirsty guest!',wrongTool:'That is a lot of watering can. Try a cup.'},
 {id:'backpack',title:'Return the teal backpack',prompt:'Find a backpack',context:['Teal backpack','Red backpack'],tool:['Lost-property map','Leaf blower'],success:'Their backpack is back!',missing:'Two bags. Whose is it? Add the color.',wrongContext:'Nice bag. Wrong color!',wrongTool:'The leaves moved. The backpack did not.'},
 {id:'stage',title:'Get the stage ready',prompt:'Light the stage',context:['Stage at dusk','Picnic table'],tool:['Stage switch','Flashlight'],success:'The stage is ready. Let’s dance!',missing:'A lovely picnic light. Add where to shine.',wrongContext:'The picnic looks lovely. The stage is dark.',wrongTool:'One tiny spotlight. Try the stage switch.'}
];
export function ingredients(challenge){return [
 {id:'prompt',kind:'prompt',name:challenge.prompt,color:'#ed7850',symbol:'✦'},
 {id:'context0',kind:'context',name:challenge.context[0],color:'#a08ada',symbol:'◎'},
 {id:'context1',kind:'context',name:challenge.context[1],color:'#a08ada',symbol:'◎'},
 {id:'tool0',kind:'tool',name:challenge.tool[0],color:'#32afab',symbol:'⚙'},
 {id:'tool1',kind:'tool',name:challenge.tool[1],color:'#32afab',symbol:'⚙'}
];}
export class MixPuzzle {
 constructor(){this.index=0;this.recipe={};this.phase='choose';this.solved=0;this.attempts=0;}
 get challenge(){return MIX_CHALLENGES[this.index];}
 get jars(){return ingredients(this.challenge);}
 add(id){if(this.phase!=='choose')return false;const item=this.jars.find(p=>p.id===id);if(!item)return false;this.recipe[item.kind]=id;return true;}
 remove(kind){if(this.phase!=='choose')return false;delete this.recipe[kind];return true;}
 run(){if(this.phase!=='choose'||!this.recipe.prompt)return null;this.phase='running';this.attempts++;const r=this.recipe;this.outcome=!r.context?'missing':r.context!=='context0'?'context':r.tool!=='tool0'?'tool':'success';return this.outcome;}
 settle(){if(this.phase!=='running')return false;this.phase=this.outcome==='success'?'success':'choose';if(this.phase==='success')this.solved++;return true;}
 next(){if(this.phase!=='success')return false;if(this.index===2){this.phase='complete';return true;}this.index++;this.recipe={};this.phase='choose';return true;}
}
const V=(...p)=>new THREE.Vector3(...p);
const material=(color,extra={})=>new THREE.MeshStandardMaterial({color,roughness:.65,...extra});
function box(parent,name,size,position,mat){const o=new THREE.Mesh(new THREE.BoxGeometry(...size),mat);o.name=name;o.position.fromArray(position);o.castShadow=o.receiveShadow=true;parent.add(o);return o;}
function cylinder(parent,name,rt,rb,h,position,mat){const o=new THREE.Mesh(new THREE.CylinderGeometry(rt,rb,h,24),mat);o.name=name;o.position.fromArray(position);o.castShadow=o.receiveShadow=true;parent.add(o);return o;}
function label(text,color='#234b45',background='#fff1ce',width=512,height=160){const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const ctx=canvas.getContext('2d');ctx.fillStyle=background;ctx.fillRect(0,0,width,height);ctx.fillStyle=color;ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='bold 44px Trebuchet MS';const words=text.split(' ');let line='',lines=[];for(const word of words){if(ctx.measureText(line+' '+word).width>width-30&&line){lines.push(line);line=word;}else line+=(line?' ':'')+word;}lines.push(line);lines.forEach((s,i)=>ctx.fillText(s,width/2,height/2+(i-(lines.length-1)/2)*49));const t=new THREE.CanvasTexture(canvas);t.colorSpace=THREE.SRGBColorSpace;return new THREE.MeshBasicMaterial({map:t,side:THREE.DoubleSide});}
function paper(parent,text,size,position,color){const o=new THREE.Mesh(new THREE.PlaneGeometry(...size),label(text,color));o.position.fromArray(position);parent.add(o);return o;}
function template(kit,library,asset){const scene=kit.libraries.get(library).scene;let source;scene.traverse(o=>{if(o.userData.asset_id===asset)source=o;});source??=scene.getObjectByName(asset);if(!source)throw Error('Missing mixer asset '+asset);const o=clone(source);o.position.set(0,0,0);o.rotation.set(0,0,0);o.traverse(n=>{if(n.isMesh){n.castShadow=n.receiveShadow=true;if(n.isSkinnedMesh)n.frustumCulled=false;}});return o;}
function poseCache(root){const cache={};root.traverse(o=>{if(o.isBone)for(const name of ['upper_arm_L','upper_arm_R','forearm_L','forearm_R','head','hand_R','hand_L','thigh_L','thigh_R','shin_L','shin_R'])if(o.name.startsWith(name))cache[name]={bone:o,q:o.quaternion.clone()};});return cache;}
function pose(root,cache,name,angle,axis=V(0,0,1)){const item=cache[name];if(!item)return;const parent=item.bone.parent.getWorldQuaternion(new THREE.Quaternion());axis.applyQuaternion(root.getWorldQuaternion(new THREE.Quaternion())).applyQuaternion(parent.invert());item.bone.quaternion.premultiply(new THREE.Quaternion().setFromAxisAngle(axis,angle));item.bone.updateWorldMatrix(false,true);}

// Position a prop by its actual handle rather than its model origin.
export function handAnchor(root,hand){return root.worldToLocal(hand.localToWorld(V(0,.055,0)));}
export function alignGrip(object,anchor,grip){object.position.copy(anchor).sub(grip.clone().applyQuaternion(object.quaternion));}

export class SkillMixer {
 constructor(engine,kit,{reduced=false,onComplete=()=>{},onWin=()=>{},onPour=()=>{}}={}){
  this.e=engine;this.kit=kit;this.reduced=reduced;this.onComplete=onComplete;this.onWin=onWin;this.onPour=onPour;this.active=false;this.root=new THREE.Group();this.root.name='SkillMixingBooth';engine.scene.add(this.root);this.root.visible=false;
  this.build();this.ray=new THREE.Raycaster();this.pointer=new THREE.Vector2();this.plane=new THREE.Plane(V(0,0,1),-2.5);this.hit=V(0,0,0);this.dragId=null;
  engine.canvas.addEventListener('pointerdown',e=>this.down(e),true);engine.canvas.addEventListener('pointermove',e=>this.move(e),true);engine.canvas.addEventListener('pointerup',e=>this.up(e),true);engine.canvas.addEventListener('pointercancel',()=>this.cancel(),true);engine.canvas.addEventListener('lostpointercapture',()=>this.cancel(),true);
 }
 build(){
  const wood=material('#98704a'),cream=material('#f4dfae'),teal=material('#246c66'),gold=material('#dfad49',{metalness:.3}),dark=material('#21423d');
  box(this.root,'Mixing bench',[3.5,.13,1.65],[0,.79,2.55],wood);for(const x of [-1.45,1.45])for(const z of [1.95,3.1])box(this.root,'Bench leg',[.12,.73,.12],[x,.36,z],wood);
  this.machine=new THREE.Group();this.machine.name='Skill mixing machine';this.machine.position.set(0,.85,1.95);this.root.add(this.machine);
  cylinder(this.machine,'Mixer foot',.44,.5,.13,[0,.065,0],dark);cylinder(this.machine,'Canvas mixer body',.37,.37,.48,[0,.33,0],teal);cylinder(this.machine,'Open funnel',.48,.25,.25,[0,.695,0],gold);cylinder(this.machine,'Funnel opening',.405,.405,.015,[0,.825,0],dark);
  this.liquid=cylinder(this.machine,'Glowing mixture',.34,.34,.015,[0,.83,0],material('#64d6bc',{emissive:'#41b38d',emissiveIntensity:.4}));paper(this.machine,'TRY A SKILL',[.59,.18],[0,.37,.377]);
  this.handle=new THREE.Group();this.handle.position.set(.42,.38,0);this.machine.add(this.handle);box(this.handle,'Crank',[.23,.05,.05],[.09,0,0],gold);box(this.handle,'Crank grip',[.065,.22,.065],[.2,.1,0],wood);
  this.stream=cylinder(this.root,'Pouring ingredient',.028,.028,.7,[0,1.95,1.95],material('#ed7850',{emissive:'#ed7850',emissiveIntensity:.3}));this.stream.visible=false;
  this.bubbles=Array.from({length:10},(_,i)=>{const o=new THREE.Mesh(new THREE.IcosahedronGeometry(.035+i%3*.012,1),material(['#ed7850','#a08ada','#32afab'][i%3],{emissive:['#ed7850','#a08ada','#32afab'][i%3],emissiveIntensity:.15}));this.root.add(o);return o;});
  this.jars=[];for(let i=0;i<5;i++){
   const g=new THREE.Group();g.name='Ingredient jar '+i;g.position.set((i-2)*.64,.86,3.02);g.userData.jarIndex=i;g.userData.home=g.position.clone();this.root.add(g);
   const color=['#ed7850','#a08ada','#a08ada','#32afab','#32afab'][i];cylinder(g,'Glazed jar',.21,.20,.39,[0,.205,0],material(color));cylinder(g,'Glass shoulder',.17,.21,.09,[0,.445,0],material('#e3ead1',{transparent:true,opacity:.55}));cylinder(g,'Cork lid',.17,.17,.075,[0,.518,0],wood);const stripe=new THREE.Mesh(new THREE.TorusGeometry(.207,.012,6,24),cream);stripe.rotation.x=Math.PI/2;stripe.position.y=.06;g.add(stripe);
   const face=paper(g,'',[.38,.20],[0,.22,.211]);g.userData.face=face;this.jars.push(g);
  }
  this.workbench=new THREE.Group();this.workbench.name='Mixing workbench';for(const object of [...this.root.children])this.workbench.add(object);this.root.add(this.workbench);
  this.helper=template(this.kit,'crowd_kit','crowd_1');this.helper.name='Mixer helper';this.root.add(this.helper);this.helperBones=poseCache(this.helper);
  this.guest=template(this.kit,'crowd_kit','crowd_5');this.guest.name='Guest who needs help';this.root.add(this.guest);this.guestBones=poseCache(this.guest);
  this.tree=new THREE.Group();this.tree.position.set(-1.35,0,-.7);this.root.add(this.tree);cylinder(this.tree,'Sapling pot',.25,.17,.35,[0,.175,0],wood);cylinder(this.tree,'Sapling trunk',.035,.06,.9,[0,.75,0],wood);for(const [x,y,z] of [[0,1.35,0],[-.22,1.12,.04],[.24,1.06,.03]]){const leaf=new THREE.Mesh(new THREE.IcosahedronGeometry(.34,1),material('#6f9559'));leaf.position.set(x,y,z);leaf.scale.y=1.25;this.tree.add(leaf);}
  this.tealPack=template(this.kit,'props_kit','backpack_teal');this.redPack=template(this.kit,'props_kit','backpack_rust');this.root.add(this.tealPack,this.redPack);for(const pack of [this.tealPack,this.redPack]){const handle=new THREE.Mesh(new THREE.TorusGeometry(.055,.012,6,16),dark);handle.name='Backpack carry handle';handle.position.set(0,.49,0);handle.scale.y=.7;pack.add(handle);}
  this.stage=new THREE.Group();this.stage.position.set(.9,0,-.8);this.root.add(this.stage);box(this.stage,'Small stage',[1.7,.22,1.15],[0,.11,0],wood);for(const x of [-.75,.75]){box(this.stage,'Stage light pole',[.045,1.9,.045],[x,.95,-.5],gold);}
  paper(this.stage,'PROMPTSTOCK',[1.45,.3],[0,1.7,-.46]);const cable=new THREE.Line(new THREE.BufferGeometry().setFromPoints([V(-.75,1.9,-.5),V(0,1.72,-.5),V(.75,1.9,-.5)]),new THREE.LineBasicMaterial({color:'#554a38'}));this.stage.add(cable);this.stageBulbs=Array.from({length:5},(_,i)=>{const o=new THREE.Mesh(new THREE.SphereGeometry(.055,10,8),material('#8c8966',{emissive:'#ffcf6b',emissiveIntensity:0}));o.position.set((i-2)*.31,1.73+Math.abs(i-2)*.065,-.5);this.stage.add(o);return o;});
  this.picnic=new THREE.Group();this.picnic.position.set(-1.5,0,-1);this.root.add(this.picnic);box(this.picnic,'Picnic table',[.9,.08,.6],[0,.5,0],wood);box(this.picnic,'Picnic leg',[.12,.5,.12],[0,.25,0],wood);
  this.picnicLamp=cylinder(this.picnic,'Picnic lantern',.085,.085,.15,[0,.63,0],material('#edc55e',{emissive:'#ffd76b',emissiveIntensity:0}));
  this.carried=new THREE.Group();this.root.add(this.carried);this.cup=new THREE.Group();this.carried.add(this.cup);cylinder(this.cup,'Cup',.062,.047,.115,[0,0,0],cream);cylinder(this.cup,'Water surface',.052,.052,.004,[0,.053,0],material('#6caaa8'));const cupHandle=new THREE.Mesh(new THREE.TorusGeometry(.035,.010,6,16),gold);cupHandle.position.x=.065;this.cup.add(cupHandle);
  this.can=new THREE.Group();this.carried.add(this.can);cylinder(this.can,'Oversized watering can',.31,.29,.48,[0,0,0],teal);const spout=cylinder(this.can,'Can spout',.07,.09,.55,[.4,.06,0],teal);spout.rotation.z=-1.0;const handle=new THREE.Mesh(new THREE.TorusGeometry(.29,.04,6,20),gold);handle.position.set(-.22,.15,0);this.can.add(handle);
  this.blower=new THREE.Group();this.carried.add(this.blower);box(this.blower,'Leaf blower',[.3,.22,.24],[0,0,0],teal);const tube=cylinder(this.blower,'Blower tube',.075,.12,.7,[.37,0,0],dark);tube.rotation.z=Math.PI/2;
  this.flashlight=new THREE.Group();this.carried.add(this.flashlight);const lightBody=cylinder(this.flashlight,'Flashlight',.09,.065,.3,[0,0,0],teal);lightBody.rotation.z=Math.PI/2;const glow=new THREE.Mesh(new THREE.ConeGeometry(.22,.95,20,1,true),new THREE.MeshBasicMaterial({color:'#fff1a7',transparent:true,opacity:.12,depthWrite:false,side:THREE.DoubleSide}));glow.rotation.z=Math.PI/2;glow.position.x=.65;this.flashlight.add(glow);
  this.drops=Array.from({length:9},()=>{const o=new THREE.Mesh(new THREE.SphereGeometry(.028,8,6),material('#7bdcdd'));this.root.add(o);return o;});
 }
 open(ui){this.ui=ui;this.puzzle=new MixPuzzle();this.active=true;this.root.visible=true;this.pouring=null;this.elapsed=0;this.completed=false;this.e.canvas.style.touchAction='none';this.e.canvas.style.cursor='grab';this.refreshChallenge();}
 refreshChallenge(){this.resultView=false;this.reveal=0;this.workbench.visible=true;this.elapsed=0;this.pouring=null;this.stream.visible=false;this.jars.forEach((o,i)=>{const face=o.userData.face;face.material.map?.dispose();face.material.dispose();face.material=label(this.puzzle.jars[i].name,'#234b45','#fff1ce',512,270);o.position.copy(o.userData.home);o.rotation.set(0,0,0);});this.resetScene();this.ui.querySelector('#playHint').textContent=this.puzzle.challenge.title;this.renderControls();}
 resetScene(){this.helper.position.set(-1.15,0,.05);this.helper.rotation.set(0,0,0);this.guest.position.set(1.0,0,.0);this.guest.rotation.set(0,0,0);this.tree.visible=this.puzzle.index===0;this.tealPack.visible=this.redPack.visible=this.puzzle.index===1;this.tealPack.position.set(.1,0,-.5);this.redPack.position.set(-.65,0,-.6);this.stage.visible=this.picnic.visible=this.puzzle.index===2;this.stageBulbs.forEach(b=>b.material.emissiveIntensity=0);this.picnicLamp.material.emissiveIntensity=0;this.tealPack.rotation.set(0,0,0);this.redPack.rotation.set(0,0,0);this.carried.visible=false;this.cup.visible=this.can.visible=this.blower.visible=this.flashlight.visible=false;this.drops.forEach(o=>o.visible=false);}
 renderControls(){const c=this.puzzle.challenge;this.ui.querySelector('#playDock').innerHTML=`<div class="mix-top"><strong>Experiment ${this.puzzle.index+1} / 3</strong><span id="mixStatus" role="status">Pick up a jar. Pour it into the funnel.</span></div><div class="mix-jars">${this.puzzle.jars.map((p,i)=>`<button data-jar="${p.id}" style="--jar:${p.color}" aria-label="Pour ${p.name}"><small>${p.kind}</small><strong>${p.name}</strong><kbd>${i+1}</kbd></button>`).join('')}</div><div class="mix-bottom"><div class="mix-recipe">${['prompt','context','tool'].map(k=>`<button data-remove="${k}" aria-label="Remove ${k}" disabled>${k} +</button>`).join('')}</div><button id="mixRun" class="primary" disabled>Mix & try</button><button id="mixNext" hidden>Next challenge →</button></div>`;
  this.ui.querySelectorAll('[data-jar]').forEach(b=>b.onclick=()=>this.pour(b.dataset.jar));this.ui.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{if(this.pouring)return;this.puzzle.remove(b.dataset.remove);this.sync();});this.ui.querySelector('#mixRun').onclick=()=>this.run();this.ui.querySelector('#mixNext').onclick=()=>this.next();this.sync();}
 say(message){const o=this.ui?.querySelector('#mixStatus');if(o)o.textContent=message;}
 sync(){if(!this.ui)return;const busy=!!this.pouring||this.puzzle.phase!=='choose';this.ui.querySelectorAll('[data-jar]').forEach(b=>{b.disabled=busy;b.setAttribute('aria-pressed',String(Object.values(this.puzzle.recipe).includes(b.dataset.jar)));});this.ui.querySelectorAll('[data-remove]').forEach(b=>{const id=this.puzzle.recipe[b.dataset.remove],p=this.puzzle.jars.find(p=>p.id===id);b.textContent=p?p.name+' ×':b.dataset.remove+' +';b.disabled=busy||!p;});this.ui.querySelector('#mixRun').disabled=busy||!this.puzzle.recipe.prompt;this.ui.querySelector('#mixRun').hidden=this.puzzle.phase==='success';const next=this.ui.querySelector('#mixNext');next.hidden=this.puzzle.phase!=='success';next.textContent=this.puzzle.index===2?'Finish experiment ✓':'Next challenge →';}
 pour(id){if(!this.active||this.pouring||this.puzzle.phase!=='choose'||!this.puzzle.add(id))return false;this.resultView=false;this.resetScene();this.pouring={index:this.puzzle.jars.findIndex(p=>p.id===id),time:0};this.onPour();this.say('Pouring '+this.puzzle.jars[this.pouring.index].name.toLowerCase()+'…');this.sync();return true;}
 run(){if(this.pouring||!this.active)return false;const outcome=this.puzzle.run();if(!outcome)return false;this.elapsed=0;this.resetScene();this.say('Let’s see what happens…');this.sync();return true;}
 next(){if(!this.active||!this.puzzle.next())return false;if(this.puzzle.phase==='complete'){if(!this.completed){this.completed=true;this.sync();this.onComplete();}}else this.refreshChallenge();return true;}
 camera(){const narrow=this.e.camera.aspect<.75,k=this.reveal||0;const start=V(0,narrow?4.2:3.6,narrow?10.0:7.65),end=V(.15,2.65,narrow?7.2:5.4);this.e.setCamera(start.lerp(end,k).toArray(),V(0,1,1.2).lerp(V(.25,.85,-.25),k).toArray());this.workbench.visible=k<.45;}
 point(e){const r=this.e.canvas.getBoundingClientRect();this.pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);this.ray.setFromCamera(this.pointer,this.e.camera);}
 down(e){if(!this.active||this.pouring||this.puzzle.phase!=='choose'||e.button!==0)return;this.point(e);const hit=this.ray.intersectObjects(this.jars,true)[0];if(!hit)return;let node=hit.object;while(node&&node.userData.jarIndex===undefined)node=node.parent;if(!node)return;this.dragIndex=node.userData.jarIndex;this.dragId=e.pointerId;this.dragStart=[e.clientX,e.clientY];this.dragged=false;this.e.canvas.setPointerCapture(e.pointerId);e.preventDefault();e.stopImmediatePropagation();}
 move(e){if(this.dragId!==e.pointerId)return;e.preventDefault();e.stopImmediatePropagation();if(Math.hypot(e.clientX-this.dragStart[0],e.clientY-this.dragStart[1])>5)this.dragged=true;if(!this.dragged)return;this.point(e);if(this.ray.ray.intersectPlane(this.plane,this.hit))this.jars[this.dragIndex].position.set(THREE.MathUtils.clamp(this.hit.x,-2,2),THREE.MathUtils.clamp(this.hit.y-.2,.8,2.6),2.5);}
 up(e){if(e.pointerId!==this.dragId)return;e.preventDefault();e.stopImmediatePropagation();const i=this.dragIndex,moved=this.dragged;this.point(e);const funnel=this.machine.localToWorld(V(0,.83,0)).project(this.e.camera),r=this.e.canvas.getBoundingClientRect(),distance=Math.hypot((this.pointer.x-funnel.x)*r.width/2,(this.pointer.y-funnel.y)*r.height/2);this.cancel();if(!moved||distance<70)this.pour(this.puzzle.jars[i].id);else this.say('Drop over the funnel, or tap a jar to pour.');}
 cancel(){const id=this.dragId;this.dragId=null;if(this.dragIndex!==undefined){const o=this.jars[this.dragIndex];o.position.copy(o.userData.home);}this.dragIndex=undefined;this.dragged=false;if(id!==null&&this.e.canvas.hasPointerCapture?.(id))this.e.canvas.releasePointerCapture(id);}
 key(e){if(!this.active||e.repeat)return;if(/^Digit[1-5]$/.test(e.code)){e.preventDefault();this.pour(this.puzzle.jars[Number(e.code.at(-1))-1].id);}if(e.code==='Enter'&&!e.target.closest('button,input')){e.preventDefault();this.puzzle.phase==='success'?this.next():this.run();}}
 update(dt,t){if(!this.active)return;dt=Math.max(0,Math.min(.1,Number.isFinite(dt)?dt:0));this.reveal=THREE.MathUtils.damp(this.reveal||0,this.resultView?1:0,this.reduced?100:6,dt);this.camera();
  for(const cache of [this.helperBones,this.guestBones])for(const p of Object.values(cache))p.bone.quaternion.copy(p.q);
  if(this.pouring){const p=this.pouring;p.time+=dt;const u=Math.min(1,p.time/(this.reduced?.18:1.15)),o=this.jars[p.index],home=o.userData.home,weight=Math.sin(Math.PI*u);o.position.copy(home).lerp(V(-.25,2.02,1.95),Math.min(1,weight*1.5));o.rotation.z=weight*-1.65;this.stream.visible=!this.reduced&&u>.25&&u<.75;this.stream.material.color.set(this.puzzle.jars[p.index].color);if(u===1){o.position.copy(home);o.rotation.z=0;this.pouring=null;this.stream.visible=false;this.say('Ready to try? Missing ingredients are experiments too.');this.sync();}}
  const running=this.puzzle.phase==='running';if(running){this.elapsed+=dt;if(this.elapsed>1.1)this.resultView=true;this.handle.rotation.x=this.reduced?0:this.elapsed*8;this.liquid.material.color.set(['#ed7850','#a08ada','#32afab'][Math.floor(this.elapsed*4)%3]);this.animateResult(this.elapsed,t);if(this.elapsed>5.2){this.puzzle.settle();const c=this.puzzle.challenge;this.say(this.puzzle.outcome==='success'?c.success:this.puzzle.outcome==='missing'?c.missing:this.puzzle.outcome==='context'?c.wrongContext:c.wrongTool);if(this.puzzle.outcome==='success')this.onWin();this.sync();if(this.puzzle.phase==='success')this.ui.querySelector('#mixNext')?.focus({preventScroll:true});}}
  else if(this.resultView)this.animateResult(5.2,t);
  this.bubbles.forEach((o,i)=>{o.visible=running&&!this.reduced&&this.elapsed<1.3;o.position.set(Math.sin(t*3+i)*.26,1.7+((t*1.5+i*.13)%1)*.55,1.95+Math.cos(t*3+i)*.22);});
 }
 animateResult(elapsed,t){const out=this.puzzle.outcome,index=this.puzzle.index,success=out==='success',act=THREE.MathUtils.smoothstep(elapsed,1.25,3.25),gesture=THREE.MathUtils.smoothstep(elapsed,3.25,4.25),nod=this.reduced?0:Math.sin((elapsed-3.25)*3)*Math.sin(Math.PI*gesture)*.07;
  const target=index===0?(out==='missing'||out==='context'?V(-1.8,0,.05):V(-.15,0,.05)):index===1?V(-.4,0,-.25):V(-.6,0,-.2);
  this.helper.position.lerpVectors(V(-1.15,0,.05),target,act);this.helper.rotation.y=Math.sin(Math.PI*act)*.25;this.helper.position.y=0;this.guest.position.y=0;
  this.helper.updateWorldMatrix(true,true);this.guest.updateWorldMatrix(true,true);
  const stride=this.reduced?0:Math.sin(act*Math.PI*4)*Math.sin(act*Math.PI)*.22;
  pose(this.helper,this.helperBones,'thigh_L',stride,V(1,0,0));pose(this.helper,this.helperBones,'thigh_R',-stride,V(1,0,0));
  pose(this.helper,this.helperBones,'shin_L',Math.max(0,-stride)*.5,V(1,0,0));pose(this.helper,this.helperBones,'shin_R',Math.max(0,stride)*.5,V(1,0,0));
  pose(this.helper,this.helperBones,'upper_arm_R',-.45*act*(1-gesture*.65),V(1,0,0));pose(this.helper,this.helperBones,'forearm_R',-.8*act*(1-gesture*.65),V(1,0,0));
  pose(this.helper,this.helperBones,'head',nod,V(1,0,0));
  // The receiving arm keeps a drink upright or lets a bag hang at the guest's side.
  if(success){const cup=index===0,bag=index===1;pose(this.guest,this.guestBones,'upper_arm_L',cup?-.42*gesture:bag?-.08*gesture:-.2*gesture,V(1,0,0));pose(this.guest,this.guestBones,'upper_arm_L',bag?-.22*gesture:-.10*gesture);pose(this.guest,this.guestBones,'forearm_L',cup?-.98*gesture:bag?-.12*gesture:-.6*gesture,V(1,0,0));
   pose(this.guest,this.guestBones,'upper_arm_R',(.18+nod)*gesture);pose(this.guest,this.guestBones,'forearm_R',-.8*gesture,V(1,0,0));pose(this.guest,this.guestBones,'head',nod,V(1,0,0));
  }else pose(this.guest,this.guestBones,'head',this.reduced?0:Math.sin(elapsed*3)*gesture*.09,V(0,1,0));
  this.helper.updateWorldMatrix(true,true);this.guest.updateWorldMatrix(true,true);
  const from=this.helperBones.hand_R?handAnchor(this.root,this.helperBones.hand_R.bone):this.helper.position.clone().add(V(.36,.94,.24));
  const to=this.guestBones.hand_L?handAnchor(this.root,this.guestBones.hand_L.bone):this.guest.position.clone().add(V(-.36,.94,.24));
  this.carried.visible=elapsed>1.25;this.carried.rotation.set(0,this.helper.rotation.y*(1-gesture),0);
  const anchor=from.clone();if(index===0&&success)anchor.lerp(to,gesture);
  alignGrip(this.carried,anchor,index===0&&out!=='tool'?V(.088,0,0):V(0,0,0));
  this.cup.visible=index===0&&out!=='tool';this.can.visible=index===0&&out==='tool';this.blower.visible=index===1&&out==='tool';this.flashlight.visible=index===2;
  if(index===1&&elapsed>1.8&&out!=='tool'){const pack=success?this.tealPack:this.redPack;pack.rotation.set(0,this.helper.rotation.y*(1-gesture),0);const carry=from.clone();if(success)carry.lerp(to,gesture);alignGrip(pack,carry,V(0,.525,0));const pickup=THREE.MathUtils.smoothstep(elapsed,1.8,2.5),home=success?V(.1,0,-.5):V(-.65,0,-.6);pack.position.lerpVectors(home,pack.position.clone(),pickup);}
  this.drops.forEach((o,i)=>{o.visible=index===0&&!success&&gesture>.3&&!this.reduced;const waterTarget=out==='missing'||out==='context'?V(-1.35,.35,-.7):V(.55,.02,.4);o.position.copy(this.carried.position).lerp(waterTarget,(t*1.6+i*.1)%1).add(V(i*.006,0,0));if(index===1&&out==='tool'){o.visible=gesture>.1&&!this.reduced;o.material.color.set('#cab973');o.scale.set(1,.25,1.7);o.position.set(.1+((t*1.2+i*.16)%1)*1.2,.1+Math.abs(Math.sin(t*4+i))*.35,-.1+i*.03);}else{o.material.color.set('#7bdcdd');o.scale.set(1,1,1);}});
  if(index===2){this.flashlight.visible=out==='tool';this.stageBulbs.forEach(b=>b.material.emissiveIntensity=success&&gesture>.2?1.5:0);this.picnicLamp.material.emissiveIntensity=(out==='context'||out==='missing')&&gesture>.2?2:0;}
 }
 close(){this.cancel();this.active=false;this.root.visible=false;this.pouring=null;this.stream.visible=false;this.ui=null;this.e.canvas.style.touchAction='';this.e.canvas.style.cursor='';}
}
