const {test}=require('node:test');const assert=require('node:assert/strict');
test('headliner unlock requires all three current-round mini-games; lifetime completions cannot bypass it',async()=>{const {concertUnlocked,migrateRound,finishActivity,finishRound}=await import('../festival-simulation.mjs');const s=migrateRound({active:true});for(const id of ['kick','aid'])finishActivity(s,id);assert.equal(concertUnlocked(s),false);finishActivity(s,'maker');assert.equal(concertUnlocked(s),true);assert.equal(finishRound(s),true);assert.equal(finishRound(s),false);assert.equal(s.finished,1);assert.equal(concertUnlocked(migrateRound(s)),true);assert.equal(concertUnlocked(migrateRound({finished:1})),false);assert.equal(concertUnlocked(migrateRound({completed:['kick','kick','kick','kick']})),false);});
test('concert cameras remain continuous, above the lawn and finite through the full song',async()=>{const {concertCamera}=await import('../festival-concert.mjs');for(const aspect of [.5,1.6,2.4]){let prev=concertCamera(0,{aspect});for(let t=.1;t<=195;t+=.1){const c=concertCamera(t,{aspect});assert.ok([...c.position,...c.target].every(Number.isFinite));assert.ok(c.position[1]>=2.9);assert.ok(Math.hypot(...c.position.map((n,i)=>n-prev.position[i]))<.25);prev=c;}assert.deepEqual(concertCamera(0,{steady:true,aspect}),concertCamera(190,{steady:true,aspect}));}});
test('concert does not loop, replaces records without overlap and emits an actual ending',async()=>{const {FestivalMusic,FINALE_TRACK}=await import('../festival-music.mjs');class Audio{constructor(){this.events={};this.currentTime=0;this.duration=194;}addEventListener(t,f){this.events[t]=f;}pause(){this.paused=true;this.events.pause?.();}removeAttribute(){this.src='';}load(){}async play(){this.paused=false;this.events.playing?.();}}const m=new FestivalMusic({fadeMs:0,AudioClass:Audio});await m.playRecord('Solve');const old=m.track;await m.playFinale();assert.equal(old.paused,true);assert.equal(old.src,'');assert.equal(m.track.src,FINALE_TRACK.src);assert.equal(m.track.loop,false);m.track.currentTime=37;m.pause();await m.play();assert.equal(m.state.currentTime,37);m.track.events.ended();assert.equal(m.state.status,'ended');assert.equal(m.state.playing,false);await m.playFinale();assert.equal(m.state.currentTime,0);assert.equal(m.track.loop,false);});
test('multi-material crowd parts share the same seat and original matrices are restored on exit',async()=>{const THREE=await import('three');const {FestivalConcert}=await import('../festival-concert.mjs');const group=new THREE.Group(),batches=[];for(let part=0;part<3;part++){const b=new THREE.InstancedMesh(new THREE.BoxGeometry(),new THREE.MeshStandardMaterial(),4);b.name='Festival guests 1 idle';b.castShadow=true;for(let i=0;i<4;i++)b.setMatrixAt(i,new THREE.Matrix4().makeTranslation(i,0,part));group.add(b);batches.push(b);}const robot=new THREE.Group();robot.position.set(12,0,3);robot.visible=false;const e={scene:new THREE.Scene(),batches:[]},kit={group,instances:new Map([['robot',robot]])};const c=new FestivalConcert(e,kit);c.built=true;c.root=new THREE.Group();c.props=[];c.update=()=>{};const before=batches.map(b=>b.instanceMatrix.array.slice());c.open();for(let part=1;part<3;part++)for(let i=0;i<4;i++)assert.deepEqual(c.batches[part].positions[i].p,c.batches[0].positions[i].p);assert.notEqual(robot.position.x,12);assert.equal(robot.visible,true);batches.forEach(b=>assert.equal(b.castShadow,false));c.close();assert.equal(robot.visible,false);batches.forEach(b=>assert.equal(b.castShadow,true));assert.deepEqual(robot.position.toArray(),[12,0,3]);batches.forEach((b,i)=>assert.deepEqual(b.instanceMatrix.array,before[i]));assert.equal(c.root.visible,false);});
test('the last challenge sends the player back to explore instead of auto-opening the concert',async()=>{
 const {FestivalPlay}=await import('../festival-play.mjs');const {migrateRound,finishActivity}=await import('../festival-simulation.mjs');const p=Object.create(FestivalPlay.prototype),opened=[];let action;
 Object.assign(p,{state:migrateRound({active:true,completed:['kick','aid']}),clock:10,complete(id){finishActivity(this.state,id);},hint(){},button(id,fn){action=fn;},ui:{querySelector:()=>({insertAdjacentHTML(){},focus(){}})},profile:[],lastFrame:0,ambient(){},open(id){opened.push(id);},exit(){this.active=null;}});
 p.result('maker','Done');assert.equal(p.finaleAt,undefined);action();p.update(.01,13);assert.deepEqual(opened,[]);assert.equal(p.canAttendConcert(),true);
});
test('entering the festival begins exploration and preserves an unfinished visit',async()=>{
 const {FestivalPlay}=await import('../festival-play.mjs');const {migrateRound}=await import('../festival-simulation.mjs');const p=Object.create(FestivalPlay.prototype);let entered=0,journals=0;
 Object.assign(p,{state:migrateRound({active:false,finished:2,completed:['kick','aid','maker'],best:300}),exit(){},save(){},h:{prepare(){entered++;},showJournal(){journals++;}}});
 p.startRound();assert.equal(entered,1);assert.deepEqual(p.state.completed,[]);assert.equal(p.canAttendConcert(),false);assert.equal(p.state.best,300);
 p.state.completed=['aid'];p.startRound();assert.deepEqual(p.state.completed,['aid']);p.continueRound();assert.equal(journals,1);
});
test('first-person exploration hides the player; kick, concert and asset review show it',async()=>{
 const {FestivalPlay}=await import('../festival-play.mjs');const p=Object.create(FestivalPlay.prototype);p.hero={visible:true};p.e={};
 for(const [active,visible]of [[null,false],['kick',true],['maker',false],['aid',false],['records',false],['canoe',false],['finale',true],[null,false]]){p.active=active;p.syncHeroVisibility();assert.equal(p.hero.visible,visible,`camera mode ${active}`);}
 p.e.jamReview={};p.syncHeroVisibility();assert.equal(p.hero.visible,true);
});
test('extra festival guests form spaced social groups and leave the kick course and lake clear',async()=>{
 const {EXTRA_FESTIVAL_GUESTS:guests}=await import('../festival-crowd.mjs');assert.equal(guests.length,48);
 guests.forEach(([x,z,r],i)=>{assert.ok([x,z,r].every(Number.isFinite));assert.ok(z>-45);assert.ok(!(Math.abs(x)<7&&z>12&&z<31));for(const [a,b]of guests.slice(i+1))assert.ok(Math.hypot(x-a,z-b)>1.5);});
});
test('concert layout mixes model order and reserves collision-free companion space',async()=>{
 const {concertSeats,FEATURED_SEATS}=await import('../concert-layout.mjs');const seats=concertSeats(73);assert.deepEqual(seats,concertSeats(73));
 const all=[...FEATURED_SEATS,...seats.map(s=>[s.x,s.z])];for(let i=0;i<all.length;i++)for(let j=i+1;j<all.length;j++)assert.ok(Math.hypot(all[i][0]-all[j][0],all[i][1]-all[j][1])>1.35,`overlap ${i}/${j}`);
 // Adjacent model-group entries must spread across the lawn, not fill one row.
 for(let i=0;i<60;i+=12){const z=seats.slice(i,i+12).map(s=>s.z);assert.ok(Math.max(...z)-Math.min(...z)>6);}
});
