const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
let THREE;
async function fixture(){
 THREE=await import('three');const FestivalCrowd=await import('../festival-crowd.mjs');const {FestivalEngine}=await import('../engine-source.mjs');
 const noop=()=>{};const ctx2d=new Proxy({}, {get:(_,key)=>key==='measureText'?text=>({width:text.length*12}):noop,set:()=>true});
 const ctx=vm.createContext({console,Float32Array,URL,document:{createElement:()=>({getContext:()=>ctx2d}),addEventListener:noop},window:{FestivalCrowd,FestivalEngine,addEventListener:noop},localStorage:{getItem:()=>null},matchMedia:()=>({matches:false})});
 const h=fs.readFileSync(path.join(__dirname,'../skills-jam-3d.html'),'utf8');for(const m of h.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g))vm.runInContext(m[1].replace(/\bboot\(\);\s*$/,''),ctx);
 const e=Object.create(FestivalEngine.prototype);Object.assign(e,{scene:new THREE.Scene(),geometries:new Map(),materials:new Map(),batches:[],time:{value:0},sun:new THREE.DirectionalLight(),texture:()=>null,low:false,dusk:0});e.sun.position.set(-50,90,-40);
 ctx.adapter=e;vm.runInContext('engine=adapter;posterTexture={id:"poster",gl:null};foliageTexture={id:"foliage",gl:null};buildWorld();',ctx);return{e,ctx};
}
let ready;const world=()=>ready??=fixture();
test('festival geometry is rendered by Three.js instanced PBR meshes',async()=>{const{e}=await world();assert.ok(e.batches.length>10);assert.ok(e.batches.every(b=>b.mesh.isInstancedMesh&&b.mesh.material.isMeshStandardMaterial));assert.ok(e.batches.reduce((n,b)=>n+b.nodes.length,0)>10000);});
test('foliage preserves transparency and matching alpha shadows',async()=>{const{e}=await world();const b=e.batches.find(b=>b.nodes[0].tex?.id==='foliage');assert.ok(b);assert.equal(b.mesh.material.alphaTest,.28);assert.equal(b.mesh.customDepthMaterial.alphaTest,.28);assert.equal(b.mesh.castShadow,true);});
test('meadow keeps gameplay paths and the concert gathering area clear with ankle-height blades',async()=>{const{e}=await world();const {createMeadow}=await import('../festival-graphics.mjs');const meadow=createMeadow(e,(x,z)=>Math.abs(x)<2,(x,z)=>x>20&&z>10);const m=new THREE.Matrix4(),p=new THREE.Vector3(),q=new THREE.Quaternion(),s=new THREE.Vector3();assert.ok(meadow.count>1000&&meadow.count<80000);for(let i=0;i<meadow.count;i++){meadow.getMatrixAt(i,m);m.decompose(p,q,s);assert.ok(Math.abs(p.x)>=2);assert.ok(!(p.x>20&&p.z>10));assert.ok(!(Math.abs(p.x)<10&&p.z<-20&&p.z>-32));assert.ok(s.y>=.069&&s.y<=.211);}});
test('refined kit crowns keep gameplay pivots and share the foliage shadow silhouette',async()=>{const{e}=await world();const {refineKitCanopies}=await import('../festival-graphics.mjs');const root=new THREE.Group();root.position.set(7,0,-5);const original=new THREE.Mesh(new THREE.SphereGeometry(),new THREE.MeshStandardMaterial());original.material.name='foliage_card';root.add(original);const kit={instances:new Map([['kit_tree_oak',root]])};refineKitCanopies(e,kit);refineKitCanopies(e,kit);assert.deepEqual(root.position.toArray(),[7,0,-5]);assert.equal(original.visible,false);const cards=root.getObjectByName('kit_tree_oak_leaf_clusters');assert.equal(root.children.length,2);assert.equal(cards.count,70);assert.equal(cards.material.alphaTest,cards.customDepthMaterial.alphaTest);assert.ok(cards.geometry.attributes.position.count>6);assert.ok(Array.from(cards.instanceMatrix.array).every(Number.isFinite));});
test('lake uses Three.js reflective Water instead of the old box shader',async()=>{const{e}=await world();assert.equal(e.water.isWater,true);assert.equal(e.water.geometry.type,'PlaneGeometry');assert.ok(e.water.material.uniforms.normalSampler.value.isDataTexture);assert.ok(e.batches.every(b=>b.nodes[0].props[1]!==3));});
test('animated character transforms transfer to Three.js instance matrices',async()=>{const{e,ctx}=await world();vm.runInContext('animators.forEach(fn=>fn(13));',ctx);const b=e.batches.find(b=>b.dirty);assert.ok(b);e.fire={intensity:0};e.updateLighting=()=>{};e.composer={render(){}};e.renderer={setRenderTarget(){}};e.frame=0;e.postprocessingSupported=true;e.draw(13);const m=new THREE.Matrix4();b.mesh.getMatrixAt(0,m);assert.deepEqual(m.elements,Array.from(b.data.slice(0,16)));assert.equal(b.dirty,false);assert.equal(e.water.material.uniforms.time.value,13*.35);});
test('blank postprocessing falls back once to direct rendering',async()=>{const {FestivalEngine}=await import('../engine-source.mjs');let renders=0,reads=0;const e=Object.create(FestivalEngine.prototype);Object.assign(e,{frame:0,time:{value:0},batches:[],dusk:0,fire:{},updateLighting(){},composer:{render(){}},renderer:{setRenderTarget(){},render(){renders++;},getContext(){return{drawingBufferWidth:10,drawingBufferHeight:10,RGBA:1,UNSIGNED_BYTE:1,readPixels(x,y,w,h,f,t,p){reads++;p.fill(0);}};}}});e.draw(0);e.draw(1);assert.equal(e.postprocessingSupported,false);assert.equal(reads,1);assert.equal(renders,2);});
