const{test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');
const kits=['tent_kit','props_kit','player_jam','crowd_kit','world_dressing'];
const glbs=Object.fromEntries(kits.map(k=>{const b=fs.readFileSync(`assets/models/${k}.glb`);assert.equal(b.toString('ascii',0,4),'glTF');return[k,JSON.parse(b.toString('utf8',20,20+b.readUInt32LE(12)))];}));
test('all five model libraries contain meshes and no studio objects',()=>{for(const j of Object.values(glbs)){assert.ok(j.meshes.length>0);assert.ok(!j.cameras?.length);assert.ok(!j.extensions?.KHR_lights_punctual);}});
test('all placed roots resolve to exported reusable assets',()=>{for(const p of JSON.parse(fs.readFileSync('assets/models/layout.json')).placements){assert.ok(glbs[p.library].nodes.some(n=>n.name===p.asset),p.asset);assert.ok(p.position.every(Number.isFinite));}});
test('player exports idle walk kick with animation channels',()=>{const clips=glbs.player_jam.animations;assert.deepEqual(clips.map(c=>c.name).sort(),['idle','kick','walk']);for(const c of clips)assert.ok(c.channels.length>=3);});
test('evaluated meshes stay within requested per-asset budgets and metre scale',()=>{const r=JSON.parse(fs.readFileSync('art/skills-jam/REPORT.json'));for(const a of r.tent_kit)assert.ok(a.triangles<4000,a.name);for(const a of r.props_kit)assert.ok(a.triangles<1500,a.name);assert.ok(r.player_jam[0].triangles<15000);assert.ok(Math.abs(r.player_jam[0].size_xyz_m[2]-1.85)<.05);for(const a of r.props_kit.filter(a=>a.name.startsWith('record_')&&a.name!=='record_table'))assert.equal(a.size_xyz_m[0],.3);const b=r.props_kit.find(a=>a.name==='kickball_globe');for(let i=0;i<3;i++)assert.ok(Math.abs(b.bbox_blender_min[i]+b.bbox_blender_max[i])<1e-6);});
test('asset metadata cannot collide with Three.js pivot reconstruction',()=>{for(const j of Object.values(glbs))for(const n of j.nodes)assert.equal(n.extras?.pivot,undefined);});
test('the retriever carries its fur texture inside the GLB and companions retain floor-contact scale',()=>{const j=glbs.crowd_kit,material=j.materials.find(m=>m.name==='companion_fur');assert.ok(material?.pbrMetallicRoughness.baseColorTexture,'fur must survive export');const texture=j.textures[material.pbrMetallicRoughness.baseColorTexture.index];assert.ok(j.images[texture.source].bufferView!==undefined,'no external texture dependency');const report=JSON.parse(fs.readFileSync('art/skills-jam/REPORT.json'));for(const [kit,name,maxHeight] of [['crowd_kit','golden_retriever',1.05],['props_kit','first_aid_robot',1.25]]){const asset=report[kit].find(a=>a.name===name);assert.ok(asset.bbox_blender_min[2]>=-.025&&asset.bbox_blender_min[2]<.03,name+' feet meet ground');assert.ok(asset.size_xyz_m[2]<maxHeight&&asset.size_xyz_m[2]>.8,name+' matches human scale');}});
test('actual GLTFLoader placement produces finite matrices and playable clips',async()=>{
 const THREE=await import('three');const{GLTFLoader}=await import('three/addons/loaders/GLTFLoader.js');const{JamKit}=await import('../jam-kit.mjs');
 // Geometry/animation integration test; image decoding is covered by browser review.
 const loader=new GLTFLoader();loader.register(parser=>{parser.loadTexture=async()=>new THREE.Texture();return{name:'test_texture_decoder'};});
 const libraries=new Map();for(const k of kits){const b=fs.readFileSync(`assets/models/${k}.glb`);libraries.set(k,await loader.parseAsync(b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength),''));}
 const engine={scene:new THREE.Scene(),batches:[],jamReview:true};const kit=new JamKit(engine,libraries,JSON.parse(fs.readFileSync('assets/models/layout.json')));kit.update(.5);engine.scene.updateMatrixWorld(true);engine.scene.traverse(o=>assert.ok(o.matrixWorld.elements.every(Number.isFinite),o.name));assert.ok(kit.play('hero','walk'));assert.ok(kit.play('hero','idle'));assert.ok(kit.play('hero','kick'));assert.equal(kit.play('hero','missing'),false);
 const robot=new THREE.Box3().setFromObject(kit.instances.get('robot'));assert.ok(robot.min.z>1.46,'robot clears front edge of original bench');
});
