const {test}=require('node:test');const assert=require('node:assert/strict');
const sim=()=>import('../festival-simulation.mjs');
test('fixed timestep produces equivalent kicks across display rates',async()=>{const {KickBall}=await sim();const positions=[];for(const hz of [30,60,120]){const b=new KickBall();b.kick(.16,.55);for(let i=0;i<hz*3;i++)b.advance(1/hz);positions.push(b.p);}for(const p of positions)for(let i=0;i<3;i++)assert.ok(Math.abs(p[i]-positions[0][i])<1e-8);});
test('prediction and actual kick follow the same trajectory',async()=>{const {KickBall,STEP}=await sim();const b=new KickBall();const points=b.predict(.1,.4);b.kick(.1,.4);for(let i=0;i<points.length;i++){b.tick();assert.deepEqual(b.p,points[i]);for(let j=0;j<7;j++)b.tick();}});
test('ball reflects away from obstacles and resets inaccessible positions',async()=>{const {KickBall}=await sim();const b=new KickBall({obstacles:[{x:0,z:20,r:1}]});b.p=[.8,.13,20];b.v=[-3,0,0];b.moving=true;b.tick();assert.ok(b.p[0]>=1.13);assert.ok(b.v[0]>0);b.p=[50,1,0];b.tick();assert.deepEqual(b.p,[-4,.13,27]);});
test('round progress migrates defensively and completion is idempotent',async()=>{const {migrateRound,finishActivity,nextActivity,finishRound}=await sim();const s=migrateRound({active:true,completed:['records','records','invalid'],day:-3,best:'bad'});assert.deepEqual(s.completed,[]);assert.equal(s.day,1);assert.equal(s.best,0);assert.equal(finishActivity(s,'records'),false);assert.equal(finishRound(s),false);for(const id of ['kick','aid','maker'])assert.equal(finishActivity(s,id),true);assert.equal(nextActivity(s),'finale');assert.equal(finishRound(s),true);assert.equal(finishRound(s),false);assert.equal(s.finished,1);});
test('assisted strength can reach each day-one target',async()=>{const {KickBall}=await sim();for(const [x,z] of [[-7,20],[0,17],[-5,14]]){const b=new KickBall();const angle=Math.atan2(x-b.p[0],b.p[2]-z);let best=Infinity;for(let i=0;i<=100;i++)for(const p of b.predict(angle,i/100))if(p[1]<.55)best=Math.min(best,Math.hypot(p[0]-x,p[2]-z));assert.ok(best<.83,`${x},${z}: ${best}`);}});
test('static batching preserves asset bounds while reducing draw primitives',async()=>{const THREE=await import('three');const {compactStaticAsset}=await import('../jam-kit.mjs');const root=new THREE.Group();root.position.set(3,0,-4);const material=new THREE.MeshStandardMaterial();for(let i=0;i<8;i++){const m=new THREE.Mesh(new THREE.BoxGeometry(.3,1,.4),material);m.position.set(i*.4,.5,0);root.add(m);}const before=new THREE.Box3().setFromObject(root);compactStaticAsset(root);const after=new THREE.Box3().setFromObject(root);assert.equal(root.children.length,1);assert.ok(before.min.distanceTo(after.min)<1e-6);assert.ok(before.max.distanceTo(after.max)<1e-6);});
async function loadPlayer(){const fs=require('node:fs');const THREE=await import('three');const {createJamGltfLoader}=await import('../jam-kit.mjs');const loader=await createJamGltfLoader();loader.register(p=>{p.loadTexture=async()=>new THREE.Texture();return{name:'texture_stub'};});const b=fs.readFileSync('assets/models/player_jam.glb');return {THREE,g:await loader.parseAsync(b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength),'')};}
test('skinned kicking foot reaches the gameplay ball at the contact cue',async()=>{
 const {THREE,g}=await loadPlayer();const mixer=new THREE.AnimationMixer(g.scene);mixer.clipAction(g.animations.find(c=>c.name==='kick')).play();mixer.setTime(.5);g.scene.updateMatrixWorld(true);
 const box=new THREE.Box3(),v=new THREE.Vector3();let vertices=0;
 g.scene.traverse(o=>{if(!o.isSkinnedMesh||!o.name.includes('shoes'))return;o.skeleton.update();const foot=o.skeleton.bones.findIndex(b=>b.name==='foot_R');assert.ok(foot>=0);
  for(let i=0;i<o.geometry.attributes.position.count;i++){if(o.geometry.attributes.skinIndex.getX(i)!==foot)continue;o.getVertexPosition(i,v);box.expandByPoint(v.applyMatrix4(o.matrixWorld));vertices++;}
 });assert.ok(vertices>30);assert.ok(box.min.y>-.025);assert.ok(box.intersectsSphere(new THREE.Sphere(new THREE.Vector3(0,.13,.5),.13)));
});
test('authored skin weights are normalized and blend across knees and elbows',async()=>{
 const {g}=await loadPlayer();let blended=0,meshes=0;
 g.scene.traverse(o=>{if(!o.isSkinnedMesh)return;meshes++;const weights=o.geometry.attributes.skinWeight,indices=o.geometry.attributes.skinIndex;
  for(let i=0;i<weights.count;i++){const w=[weights.getX(i),weights.getY(i),weights.getZ(i),weights.getW(i)];assert.ok(Math.abs(w.reduce((a,b)=>a+b,0)-1)<.001);if(w.filter(v=>v>.05).length>1)blended++;for(let k=0;k<4;k++)if(w[k]>0)assert.ok(indices.getComponent(i,k)<o.skeleton.bones.length);}
 });assert.ok(meshes>=6);assert.ok(blended>100);assert.deepEqual(g.animations.map(c=>c.name).sort(),['idle','kick','walk']);
});
test('baked crowd geometry preserves the posed skin without sharing mutable vertices',async()=>{
 const {THREE,g}=await loadPlayer();const {bakeCrowdTemplate}=await import('../jam-kit.mjs');const source=g.scene.getObjectByName('player_jam');const mixer=new THREE.AnimationMixer(g.scene);mixer.clipAction(g.animations.find(c=>c.name==='kick')).play();mixer.setTime(.5);g.scene.updateMatrixWorld(true);
 const before=new THREE.Box3(),v=new THREE.Vector3();source.traverse(o=>{if(!o.isSkinnedMesh)return;o.skeleton.update();for(let i=0;i<o.geometry.attributes.position.count;i++){o.getVertexPosition(i,v);before.expandByPoint(v.applyMatrix4(o.matrixWorld));}});
 const baked=bakeCrowdTemplate(source);const after=new THREE.Box3().setFromObject(baked);assert.ok(before.min.distanceTo(after.min)<1e-5);assert.ok(before.max.distanceTo(after.max)<1e-5);baked.traverse(o=>{assert.ok(!o.isSkinnedMesh);if(o.isMesh)assert.equal(o.geometry.attributes.skinWeight,undefined);});
});
