"""Measure kit roots → art/skills-jam/REPORT.json (+ optional MEASUREMENTS.md).

Prefer measuring from editable .blend files. If a blend is missing, fall back to
importing the shipped GLB so budgets can be refreshed without artist sources.

Usage (repo root):
  blender --background --python art/skills-jam/blender/measure_kits.py
  blender --background --python art/skills-jam/blender/measure_kits.py -- --kit tent_kit
  blender --background --python art/skills-jam/blender/measure_kits.py -- --write-md
"""
from __future__ import annotations

import json
import math
import sys
from pathlib import Path

import bpy
from mathutils import Vector

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
MANIFEST_PATH = HERE / "kits.manifest.json"


def _argv_after_double_dash():
    if "--" in sys.argv:
        return sys.argv[sys.argv.index("--") + 1 :]
    return []


def load_manifest():
    return json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))


def reset_scene():
    bpy.ops.wm.read_factory_settings(use_empty=True)


def find_root(name: str):
    obj = bpy.data.objects.get(name)
    if obj:
        return obj
    for o in bpy.data.objects:
        if o.get("asset_id") == name:
            return o
    return None


def mesh_objects(root):
    out = []
    stack = [root]
    while stack:
        o = stack.pop()
        if o.type == "MESH":
            out.append(o)
        stack.extend(list(o.children))
    return out


def count_triangles(root) -> int:
    total = 0
    for o in mesh_objects(root):
        mesh = o.data
        mesh.calc_loop_triangles()
        total += len(mesh.loop_triangles)
    return total


def primitive_batches(root) -> int:
    """Rough draw-batch proxy: one batch per material slot on each mesh."""
    batches = 0
    for o in mesh_objects(root):
        batches += max(1, len(o.material_slots))
    return batches


def world_bbox(root):
    """Axis-aligned bbox in Blender world space (Z-up)."""
    depsgraph = bpy.context.evaluated_depsgraph_get()
    corners = []
    for o in mesh_objects(root):
        eval_obj = o.evaluated_get(depsgraph)
        mesh = eval_obj.to_mesh()
        try:
            mat = eval_obj.matrix_world
            for v in mesh.vertices:
                corners.append(mat @ v.co)
        finally:
            eval_obj.to_mesh_clear()
    if not corners:
        # Fallback: object bound_box
        mat = root.matrix_world
        for corner in root.bound_box:
            corners.append(mat @ Vector(corner))
    xs = [c.x for c in corners]
    ys = [c.y for c in corners]
    zs = [c.z for c in corners]
    mn = Vector((min(xs), min(ys), min(zs)))
    mx = Vector((max(xs), max(ys), max(zs)))
    return mn, mx


def measure_root(root, eye_height: float) -> dict:
    mn, mx = world_bbox(root)
    size = mx - mn
    return {
        "name": root.get("asset_id", root.name),
        "triangles": count_triangles(root),
        "primitive_batches": primitive_batches(root),
        "bbox_blender_min": [mn.x, mn.y, mn.z],
        "bbox_blender_max": [mx.x, mx.y, mx.z],
        "size_xyz_m": [
            round(size.x, 4) if size.x > 1e-6 else round(size.x, 6),
            round(size.y, 4) if size.y > 1e-6 else round(size.y, 6),
            round(size.z, 4) if size.z > 1e-6 else round(size.z, 6),
        ],
        "height_vs_eye": round(size.z / eye_height, 3) if eye_height else None,
    }


def load_kit_scene(kit: dict) -> str:
    """Open blend or import GLB. Returns source label."""
    blend = HERE / kit["blend"]
    glb = ROOT / "assets" / "models" / kit["glb"]
    reset_scene()
    if blend.is_file():
        bpy.ops.wm.open_mainfile(filepath=str(blend))
        return f"blend:{blend.name}"
    if glb.is_file():
        bpy.ops.import_scene.gltf(filepath=str(glb))
        return f"glb:{kit['glb']}"
    raise FileNotFoundError(
        f"No source for {kit['id']}: need {blend.name} or shipped {kit['glb']}"
    )


def round_bbox(entry: dict) -> dict:
    """Keep REPORT.json readable; preserve float fidelity similar to prior exports."""
    for key in ("bbox_blender_min", "bbox_blender_max"):
        entry[key] = [float(v) for v in entry[key]]
    return entry


def measure_kit(kit: dict, eye_height: float) -> tuple[list[dict], str]:
    source = load_kit_scene(kit)
    rows = []
    missing = []
    for name in kit["roots"]:
        root = find_root(name)
        if not root:
            missing.append(name)
            continue
        rows.append(round_bbox(measure_root(root, eye_height)))
    if missing:
        raise RuntimeError(f"{kit['id']} missing roots ({source}): {', '.join(missing)}")
    return rows, source


def write_measurements_md(report: dict, sources: dict, budgets: dict):
    lines = [
        "# Kit measurements",
        "",
        "Generated by `art/skills-jam/blender/measure_kits.py`.",
        "Triangle / bbox budgets are enforced by `npm run check:glb-budgets` and `tests/kit.test.cjs`.",
        "",
    ]
    for kit_id, rows in report.items():
        lines.append(f"## {kit_id}")
        lines.append(f"Source: `{sources.get(kit_id, '?')}`")
        lines.append("")
        lines.append("| Asset | Tris | Size XYZ (m) | Height÷eye |")
        lines.append("| --- | ---: | --- | ---: |")
        for a in rows:
            size = "×".join(str(v) for v in a["size_xyz_m"])
            lines.append(
                f"| `{a['name']}` | {a['triangles']} | {size} | {a.get('height_vs_eye', '')} |"
            )
        lines.append("")
    lines.append("## Byte ceilings (guidelines)")
    lines.append("")
    for name, ceiling in budgets.items():
        lines.append(f"- `{name}` ≤ {ceiling} bytes")
    lines.append("")
    path = HERE.parent / "MEASUREMENTS.md"
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {path.relative_to(ROOT)}")


def main():
    args = _argv_after_double_dash()
    manifest = load_manifest()
    eye = float(manifest.get("eyeHeightM", 1.82))
    kits = manifest["kits"]

    only = None
    if "--kit" in args:
        i = args.index("--kit")
        only = args[i + 1] if i + 1 < len(args) else None

    selected = [k for k in kits if only is None or k["id"] == only]
    if only and not selected:
        raise SystemExit(f"Unknown kit id: {only}")

    # Start from existing REPORT so a single-kit run does not wipe siblings.
    report_path = ROOT / manifest.get("reportPath", "art/skills-jam/REPORT.json")
    report = {}
    if report_path.is_file():
        report = json.loads(report_path.read_text(encoding="utf-8"))

    sources = {}
    for kit in selected:
        rows, source = measure_kit(kit, eye)
        budget = kit.get("triangleBudgetPerRoot")
        if budget is not None:
            for row in rows:
                if row["triangles"] > budget:
                    print(
                        f"WARN {kit['id']}/{row['name']}: {row['triangles']} tris > budget {budget}",
                        file=sys.stderr,
                    )
        report[kit["id"]] = rows
        sources[kit["id"]] = source
        print(f"Measured {kit['id']} from {source} ({len(rows)} roots)")

    report_path.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {report_path.relative_to(ROOT)}")

    if "--write-md" in args:
        write_measurements_md(report, sources, manifest.get("byteCeilings", {}))


if __name__ == "__main__":
    main()
